In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])
y

tensor([[0.5221, 0.1867, 0.9179, 0.4950, 0.4069],
        [0.7400, 0.8465, 0.3790, 0.8590, 0.8798]])

In [6]:
y.view([1,10]) #  this is a reshape in numpy - also have to reassign - this does not do this in place

tensor([[0.5221, 0.1867, 0.9179, 0.4950, 0.4069, 0.7400, 0.8465, 0.3790, 0.8590,
         0.8798]])

In [7]:
y

tensor([[0.5221, 0.1867, 0.9179, 0.4950, 0.4069],
        [0.7400, 0.8465, 0.3790, 0.8590, 0.8798]])